name: Shell Commands

# Triggers
on: [push]

# Jobs
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Before Checkout
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List After Checkout
        run: |
          pwd
          ls